name: staff_manager

services:
  postgres:
    image: postgres:16-alpine
    container_name: staff_manager_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    networks:
      - postgres_network

  rbac_api:
    build:
      context: ./RBAC_API
      dockerfile: Dockerfile
    container_name: rbac_api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7225
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=staff_manager;Username=admin;Password=admin123
    ports:
      - "7225:7225"
    depends_on:
      - postgres
    networks:
      - postgres_network

  # Optional: pgAdmin for web-based database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network:
    driver: bridge
